### ISSUE TITLE
Having issues with the datatable.

### ISSUE THREAD

**Issue by phillipmadsen** [mpaleo/scaffolder#18]
**\* DataTables warning: table id=DataTables_Table_0 - Ajax Error***

Do we need to run a artisan command to create the initial datatable or have you looked into this at all?

do you have skype and if so will you tell me the id so we can work together like you say on your homepage. 

thanks

**Comment by mpaleo** [comment]
Hi @phillipmadsen !
I just ran the installation steps with a fresh Laravel setup but can't reproduce the problem.
Can you send me the json files (app.json + models) so I can recreate the situation ?

I think its not the point, but check the DB connection and permissions.

Thanks

PD: Email me github@michaelpaleo.com

**Comment by phillipmadsen** [comment]
emailed.

**Comment by mpaleo** [comment]
Your json files are working, I miss the last step that is to run the migrations.
I need to add this step to the docs.
`./artisan migrate`
